[package]
name = "nixify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version="4.4.0", features=["cargo", "derive"]}
nixpkgs-fmt = "1.3.0"
toml = "0.8.12"
yaml-rust2 = "0.8.0"
